//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace polowijo.gosari.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_petugas
    {
        public master_petugas()
        {
            this.trn_bongkat_muat_details_pekerja = new HashSet<trn_bongkat_muat_details_pekerja>();
        }
    
        public int ID { get; set; }
        public string NAMA_PETUGAS { get; set; }
        public polowijo.gosari.Core.Status STATUS { get; set; }
        public string STATUS_PERKAWINAN { get; set; }
        public string ALAMAT { get; set; }
        public string HANDPHONE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
    
        public virtual ICollection<trn_bongkat_muat_details_pekerja> trn_bongkat_muat_details_pekerja { get; set; }
    }
}
