//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace polowijo.gosari.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_bongkar_muat
    {
        public trn_bongkar_muat()
        {
            this.trn_bongkat_muat_details_pekerja = new HashSet<trn_bongkat_muat_details_pekerja>();
        }
    
        public int ID { get; set; }
        public System.DateTime TANGGAL_KIRIM { get; set; }
        public polowijo.gosari.Core.ItemType JENIS_BARANG { get; set; }
        public System.DateTime BERANGKAT { get; set; }
        public System.DateTime SAMPAI { get; set; }
        public System.DateTime LAMA_WAKTU { get; set; }
        public string PENGIRIM { get; set; }
        public string NOPOL { get; set; }
        public Nullable<decimal> KWANTUM { get; set; }
        public Nullable<decimal> HARGA { get; set; }
        public string NAMA_BARANG { get; set; }
        public Nullable<decimal> TOTAL_HARGA { get; set; }
        public Nullable<decimal> ONGKOS { get; set; }
        public Nullable<decimal> MUAT_KONTAINER { get; set; }
        public Nullable<decimal> HARGA_KONTAINER { get; set; }
        public Nullable<decimal> TOTAL_KONTAINER { get; set; }
        public Nullable<decimal> UANG_MAKAN { get; set; }
        public int JUMLAH_PEKERJA { get; set; }
        public int ID_BARANG { get; set; }
        public polowijo.gosari.Core.ActionType KEGIATAN { get; set; }
        public int ID_PENGIRIM { get; set; }
        public int ID_NOPOL { get; set; }
    
        public virtual ICollection<trn_bongkat_muat_details_pekerja> trn_bongkat_muat_details_pekerja { get; set; }
        public virtual master_item master_item { get; set; }
        public virtual master_supplier master_supplier { get; set; }
        public virtual master_transport master_transport { get; set; }
    }
}
